### ISSUE TITLE
About CPU only mode trainer.

### ISSUE THREAD

**Issue by PikaCat-OuO** [fairy-stockfish/variant-nnue-pytorch#17]
I found out that https://github.com/glinscott/nnue-pytorch/issues/87 managed to run the trainer on cpu only mode. 
But as I notice that at some point https://github.com/glinscott/nnue-pytorch/commit/0764091ec544446ae5852e3e7296f252a2046dd1 a custom kernel has been applied to the feature transformer.
So It means more changes need to be applied to make it work on cpu side.

But the changes of the custom kernel is so large that it's very hard to make it run on cpu? i.e. a whole bunch of changes need to be applied?

**Comment by PikaCat-OuO** [comment]
Ok, besides, If I have two bin files generated using the same configuration, how can I merge them into one bin file?

**Comment by PikaCat-OuO** [comment]
I get it. Binary concatenation. Simply copy one file to the tail of the other file.

**Comment by PikaCat-OuO** [comment]
If I encounter a problem like this：
```bash
Using c++ data loader
Traceback (most recent call last):
  File "train.py", line 97, in <module>
    main()
  File "train.py", line 92, in main
    train, val = make_data_loaders(args.train, args.val, feature_set, args.num_workers, batch_size, not args.no_smart_fen_skipping, args.random_fen_skipping, main_device)
  File "train.py", line 23, in make_data_loaders
    train = DataLoader(nnue_dataset.FixedNumBatchesDataset(train_infinite, (epoch_size + batch_size - 1) // batch_size), batch_size=None, batch_sampler=None)
  File "/notebooks/nnue_dataset.py", line 147, in __init__
    self.iter = iter(self.dataset)
  File "/notebooks/nnue_dataset.py", line 141, in __iter__
    return SparseBatchProvider(self.feature_set, self.filename, self.batch_size, cyclic=self.cyclic, num_workers=self.num_workers, filtered=self.filtered, random_fen_skipping=self.random_fen_skipping, device=self.device)
  File "/notebooks/nnue_dataset.py", line 114, in __init__
    super(SparseBatchProvider, self).__init__(
  File "/notebooks/nnue_dataset.py", line 80, in __init__
    self.stream = self.create_stream(self.feature_set, self.num_workers, self.filename, batch_size, cyclic, filtered, random_fen_skipping)
RuntimeError: ffi_prep_cif_var failed
Exception ignored in: <function TrainingDataProvider.__del__ at 0x7fa594e12ee0>
Traceback (most recent call last):
  File "/notebooks/nnue_dataset.py", line 98, in __del__
    self.destroy_stream(self.stream)
AttributeError: 'SparseBatchProvider' object has no attribute 'stream'
```
what should I do?
